version: "3.9"
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      FLASK_APP: app
    command: flask run --host=0.0.0.0 --port=5000